version: 2
updates:
  # Backend Laravel (Composer)
  - package-ecosystem: composer
    directory: /iot-projectAvalon/be-avalon
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  # Bridge MQTT (npm)
  - package-ecosystem: npm
    directory: /iot-projectAvalon/be-avalon/node_mqtt_server
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  # Frontend Vue (npm)
  - package-ecosystem: npm
    directory: /iot-projectAvalon/fe-avalon
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
